/**
 * 中文简体的提示信息
 */
var $locale_message_cn =
	[
	 	/*
	 	 * 系统提示
	 	 */
	 	{key:"sys_web_locale",					value:"zh"},
		{key:"sys_server_error",				value:"服务器异常"},
		{key:"sys_service_timeout",				value:"服务器连接超时"},
		{key:"sys_message_error",				value:"提示信息提取异常，请联系客服"},
		{key:"sys_date_error",					value:"查询开始时间不能小于结束时间，请重新设置查询条件"},
		{key:"sys_blockui_wait",				value:"<h1>请稍等...</h1>"},
		{key:"sys_common_wait",					value:"正在努力请求，请稍等..."},
		{key:"sys_common_processing",			value:"正在努力处理，请稍等..."},
		{key:"sys_common_more_operate",			value:"更多操作"},
		{key:"test", 							value:"这是一个测试的配置信息，占位符：{0}，多个占位符：{1}"},


		/*
		 * 首页
		 */
		{key:"home_no_task_data",						value:"无任务数据"},


		/*
		 * 公共
		 */
		{key:"sys_common_all", 					value:"全部"},
		{key:"sys_common_delete", 				value:"删除"},
		{key:"sys_common_add", 					value:"添加"},
		{key:"sys_common_create", 				value:"创建"},
		{key:"sys_common_select", 				value:"请选择"},
		{key:"sys_common_remark", 				value:"备注"},
		{key:"sys_common_code", 				value:"单号"},
		{key:"sys_operation_success", 			value:"操作成功"},
		{key:"sys_operation_fail", 				value:"操作失败"},

		/*
		 * 入库
		 */
		{key:"asn_title", 				value:"入库单"},
		{key:"ref_no", 					value:"参考号"},
		{key:"track_no", 				value:"跟踪号"},
		{key:"receiving", 				value:"收货"},

		{key:"customer_details", 				value:"客户详情"},
		{key:"receiving_exception_handling", 	value:"处理收货异常"},
		{key:"add_time", 						value:"添加时间"},
		{key:"update_time", 					value:"更新时间"},
		{key:"estimated_arrival", 				value:"预计到达"},

		{key:"confirm_print_asn_no", 					value:"确定打印入库单({0})吗？"},
		{key:"please_enter_expected_time", 				value:"请输入预期时间"},
		{key:"please_select_delivery_note_number", 		value:"请选择送货单号"},
		{key:"are_you_sure_forced_to_complete", 		value:"是否确认强制完成？"},
		{key:"forced_receipt_completed", 				value:"强制收货完成"},
		{key:"forced_to_move_deleted", 					value:"强制移至删除"},
		{key:"please_select_asn_code", 					value:"请选择入库单号"},
		{key:"please_fill_remarks", 					value:"请填写备注"},

		/*
		 * 出货
		 */
		{key:"please_select_the_arrival_of_the_product", 					value:"请选择到货产品"},
		{key:"documents_x_unallocated_picking_member", 						value:"单据：{0} 未分配配货员;"},

		{key:"please_enter_the_OrderCode", 								value:"请输入订单号"},
		{key:"please_enter_the_sku", 									value:"请输入产品代码"},
		{key:"sku_and_order_product_does_not_match", 					value:"产品代码：{0}与订单产品不匹配!"},
		{key:"sku_has_not_greater_than_the_number_of_scan_order_qty", 	value:"产品代码：{0}已扫描数量不可以大于订单数量!"},
		{key:"please_enter_the_code_packaging_materials", 				value:"请输入包材代码"},
		{key:"Reprint", 												value:"重新打印"},
		{key:"please_enter_picking_single", 							value:"请输入拣货单"},
		{key:"PutawayCode_x_has_been_completed", 						value:"拣货单：{0} 已全部完成"},
		{key:"BagsNo_x_completed_successfully_bagging",					value:"包袋号[{0}]完成装袋成功"},
		{key:"please_one",												value:"至少选择一个"},
		{key:"Please_add_the_price",									value:"请添加价格"},
		{key:"price_required",											value:"价格不能为空"},
		{key:"confirm_copy_logistics_price_data",						value:"确认需要复制一份物流价格数据？"},


		/*
		 * 采购单
		 */
		{key:"purchase_js_shipamount",value:"运费"},
		  {key:"purchase_js_actualamount",value:"实付"},
		  {key:"purchase_js_copeamount",value:"应付"},
		  {key:"purchase_js_amountvre",value:"付款审批退回"},
		  {key:"purchase_js_expressno",value:"快递单号"},
		  {key:"purchase_js_transitwa",value:"中转仓"},
		  {key:"purchase_js_pawa",value:"采购仓"},
		  {key:"purchase_js_systemc",value:"系统生成"},
		  {key:"purchase_js_handc",value:"手工创建"},
		  {key:"purchase_js_dseelog",value:"单击，查看采购单日志"},
		  {key:"purchase_js_dseeproduct",value:"单击，查看采购产品明细"},
		  {key:"purchase_js_buyer",value:"采购员"},
		  {key:"purchase_js_supplier",value:"供应商"},
		  {key:"purchase_js_purchase",value:"采购单"},
		  {key:"purchase_js_vrereturnflag",value:"审核退回标志"},
		  {key:"purchase_js_vrereturn",value:"审核退回"},
		  {key:"purchase_js_paystatus",value:"付款状态"},
		  {key:"purchase_js_purchasestatus",value:"采购单状态"},
		  {key:"purchase_js_prepaidproportion",value:"预付比例"},
		  {key:"js_clean",value:"关闭"},
		  {key:"js_nodata",value:"没有数据"},
		  {key:"js_select",value:"选择"},
		  {key:"purchase_js_oprationexception",value:"处理收货异常"},
		  {key:"purchase_is_responsible",value:"采购责任人"},
		  {key:"js_all",value:"全部"},
		  {key:"purchase_js_andrelated",value:"与我相关"},
		  {key:"purchase_js_paymentrequest",value:"采购付款申请"},
		  {key:"purchase_js_other",value:"其他"},
		  {key:"js_moreopration",value:"更多操作"},
		  {key:"purchase_js_printcontract",value:"打印采购合同"},
		  {key:"purchase_js_downloadcontract",value:"下载采购合同"},
		  {key:"js_view",value:"查看"},
		  {key:"js_info",value:"详细信息"},
		  {key:"sunday",value:"日"},
		  {key:"monday",value:"一"},
		  {key:"tuesday",value:"二"},
		  {key:"wednesday",value:"三"},
		  {key:"thursday",value:"四"},
		  {key:"friday",value:"五"},
		  {key:"saturday",value:"六"},
		  {key:"january",value:"01月"},
		  {key:"february",value:"02月"},
		  {key:"march",value:"03月"},
		  {key:"april",value:"04月"},
		  {key:"may",value:"05月"},
		  {key:"june",value:"06月"},
		  {key:"july",value:"07月"},
		  {key:"august",value:"08月"},
		  {key:"september",value:"09月"},
		  {key:"october",value:"10月"},
		  {key:"november",value:"11月"},
		  {key:"december",value:"12月"},
		  {key:"js_selecttime",value:"选择时间"},
		  {key:"js_selecthour",value:"小时"},
		  {key:"js_selectminute",value:"分钟"},
		  {key:"js_second",value:"秒"},
		  {key:"js_millisecond",value:"毫秒"},
		  {key:"js_current_time",value:"当前时间"},
		  {key:"js_determine",value:"确定"},
		  {key:"purchase_js_cxzf",value:"请选择要撤销(作废)的采购单"},
		  {key:"purchase_js_cxts",value:"执行撤销采购单动作后，采购单将作废。是否撤销所选中的采购单？"},
		  {key:"js_success",value:"操作成功"},
		  {key:"purchase_js_excutecount",value:"总处理单数"},
		  {key:"purchase_js_cxsuccess",value:"撤销成功单数"},
		  {key:"purchase_js_cxfail",value:"撤销失败单数"},
		  {key:"purchase_js_undlinefail",value:"以下操作失败"},
		  {key:"purchase_js_pselectqzwc",value:"请选择要强制完成的采购单"},
		  {key:"purchase_js_qzwccount",value:"强制完成单数"},
		  {key:"purchase_js_qzwcsbcount",value:"强制完成失败单数"},
		  {key:"purchase_js_plselectverify",value:"请选择审批的采购单"},
		  {key:"purchase_js_sfselectverify",value:"是否审核所选中的采购单？"},
		  {key:"purchase_js_verigysuccessc",value:"审核成功单数"},
		  {key:"purchase_js_verigyfailc",value:"审核失败单数"},
		  {key:"purchase_js_pselectprintp",value:"请选择要打印的采购单"},
		  {key:"purchase_js_pselectconfirm",value:"请选择交货确认的采购单"},
		  {key:"purchase_js_confirmtip",value:"存在重复进行交货确认的采购单.请勿勾选状态为'交货确认'的单据"},
		  {key:"purchase_js_confirmopration",value:"提交审核操作"},
		  {key:"purchase_js_pconfirmreturn",value:"请选择需要回退确认状态的采购单"},
		  {key:"purchase_js_confirmreturnyn",value:"执行撤销确认动作后，采购单将回到待确认。是否撤销采购单的确认状态？"},
		  {key:"purchase_js_createpurchase",value:"创建采购单"},
		  {key:"purchase_js_purchaseproduct",value:"产品明细"},
		  {key:"purchase_js_sqpayinfo",value:"付款申请明细"},
		  {key:"purchase_js_purchaselognull",value:"该采购单未产生采购日志"},
		  {key:"purchase_js_qzok",value:"强制完成"},
		  {key:"purchase_js_exportselect",value:"请选择要导出的采购单"},
		  {key:"purchase_js_exceptiontype",value:"异常类型"},
		  {key:"purchase_excutetype",value:"处理类型"},
		  {key:"js_receivingcode",value:"入库单"},
		  {key:"js_receivinginfo",value:"收货详情"},
		  {key:"js_detail",value:"详细"},
		  {key:"js_verify",value:"审核"},
		  {key:"purchase_js_verify",value:"审核采购单"},
		  {key:"pleace_entcount",value:"请输入数字"},
		  {key:"purchase_confirmsuccess",value:"确认成功单数"},
		  {key:"purchase_confirmfail",value:"确认失败单数"},
		  {key:"message_tip",value:"提示"},
		  {key:"purchase_pageiscantsub",value:"页面有还有未处理的错误提示，不能进行数据提交"},
		  {key:"purchase_js_verifyad",value:"审批通过"},
		  {key:"purchase_js_orderverifyad",value:"采购单审批通过"},
		  {key:"purchase_js_verinotemess",value:"备注内容非必填。可直接提交"},
		  {key:"js_submit",value:"提交"},
		  {key:"purchase_js_verifynot",value:"审批不通过"},
		  {key:"purchase_js_notnote",value:"请输入审批不通过原因"},
		  {key:"purchase_js_verifyagine",value:"提交复审"},
		  {key:"purchase_js_verifyaginenote",value:"请输入提交复审原因"},

		  {key:"purchase_js_tdayarrivals",value:"该采购单今天到货"},
		  {key:"purchase_js_tday",value:"今"},
		  {key:"purchase_js_arrivalslaterperiod",value:"该采购单到货晚期"},
		  {key:"purchase_js_laterperiod",value:"晚"},
		  {key:"purchase_js_purchaseremark",value:"单击，查看跟踪备注"},
		  {key:"purchase_js_uptrackstatus",value:"更新跟单状态"},
		  {key:"purchase_js_receivedtype",value:"请选择到货类型"},
		  {key:"purchase_js_qxzyjreceived",value:"请选择预计到货日期"},
		  {key:"purchase_js_pleasewritemark",value:"请填写备注"},
		  {key:"purchase_js_pleasemarkredate",value:"请选择需要标记到货日期的采购单"},
		  {key:"purchase_js_markisnull",value:"未找到采购单跟踪备注"},
		  {key:"purchase_js_sqpay",value:"申请付款"},
		  {key:"purchase_js_addtrackinginfo",value:"添加跟踪记录"},
		  {key:"purchase_js_auditreturn",value:"审核回退"},
		  {key:"purchase_js_auditreturnreason",value:"审核回退原因"},
		  {key:"purchase_js_enterareason",value:"请输入审核退回原因"},
		  {key:"purchase_js_returnsuccess",value:"回退成功"},
		  {key:"purchase_js_receiveddatemark",value:"未找到到货日期更新备注"},
		  {key:"purchase_js_purchasetrackstatus",value:"跟单状态"},
		  {key:"purchase_js_purchasetrackstatus_new",value:"采购跟单状态"},
		  {key:"purchase_js_financetrackstatus",value:"财务跟单状态"},
		  {key:"purchase_js_purchasetrackstatus_tip",value:"采购跟单:"},
		  {key:"purchase_js_financetrackstatus_tip",value:"财务跟单:"},
		  {key:"purchase_js_uptrackstatus_new",value:"更新采购跟单状态"},

        /*
         * 出货
         */
        {key:"please_select_the_arrival_of_the_product", 					value:"请选择到货产品"},
        {key:"documents_x_unallocated_picking_member", 						value:"单据：{0} 未分配配货员;"},

        {key:"please_enter_the_OrderCode", 								value:"请输入订单号"},
        {key:"please_enter_the_sku", 									value:"请输入产品代码"},
        {key:"sku_and_order_product_does_not_match", 					value:"产品代码：{0}与订单产品不匹配!"},
        {key:"sku_has_not_greater_than_the_number_of_scan_order_qty", 	value:"产品代码：{0}已扫描数量不可以大于订单数量!"},
        {key:"please_enter_the_code_packaging_materials", 				value:"请输入包材代码"},
        {key:"Reprint", 												value:"重新打印"},
        {key:"please_enter_picking_single", 							value:"请输入拣货单"},
        {key:"PutawayCode_x_has_been_completed", 						value:"拣货单：{0} 已全部完成"},
        {key:"BagsNo_x_completed_successfully_bagging",					value:"包袋号[{0}]完成装袋成功"},
        {key:"please_one",												value:"至少选择一个"},
        {key:"Please_add_the_price",									value:"请添加价格"},
        {key:"price_required",											value:"价格不能为空"},
        {key:"confirm_copy_logistics_price_data",						value:"确认需要复制一份物流价格数据？"},
        {key:"has_been_chosen",						value:"已选择订单"},
        {key:"picking_basket_no",						value:"篮子号"},
        {key:"order_code",						value:"订单号"},
        {key:"parcel_quantity",						value:"件数"},
        {key:"scan_quantity",						value:"已扫数"},
        {key:"additional_operating_order_tips",						value:"提示：内含附加操作订单"},
        {key:"placeholder_text_multiple",						value:"全部"},
        {key:"expected_count",						value:"预期总数"},
        {key:"real_count",						value:"实到总数"},
        {key:"receiving_exception",						value:"收货异常"},
        {key:"qc_exception",						value:"QC异常"},
	];