<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <meta http-equiv="x-ua-compatible" content="ie=7"/>
    <title>供应商平台</title>
    <script type="text/javascript" src="/js/jquery-1.8.3.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/js/jquery-myProject.js"></script>
    <script type="text/javascript" src="/js/jquery-myAjaxForm.js"></script>
    <script type="text/javascript" src="/js/init.js"></script>
    <link type="text/css" rel="stylesheet" href="/css/ui-lightness/jquery-ui.min.css?20150110"/>
    <link type="text/css" rel="stylesheet" href="/css/global.css?20150110"/>
	<link type="text/css" rel="stylesheet" href="/css/jquery.alerts.css" />
	<script type="text/javascript" src="/js/jquery.alerts.js"></script>
    <link type="text/css" rel="stylesheet" href="/css/public/index.css?20150110"/>


</head>
<body>
<?php echo $this->layout()->content;?>
<script type="text/javascript" src="/js/jquery-cookie.js"></script>
<script type="text/javascript" src="/js/jquery.form.js"></script>
<script type="text/javascript" src="/js/jquery.pagination.js"></script>
<script type="text/javascript" src="/js/mod.js"></script>
<script type="text/javascript" src="/js/jquery.myLoading.js"></script>
</body>
</html>